version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: consultas_medicas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goldenBoy
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-alpine
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ./target/consultas-medicas-0.0.1-SNAPSHOT.jar:/app/app.jar  # Corrigir o mapeamento
    command: ["java", "-jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/consultas_medicas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=goldenBoy

volumes:
  postgres-data:
